service: aws-lambda-api

frameworkVersion: "1.54.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: vito
  region: us-east-1
  environment:
    DYNAMODB_TABLE: swapi
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
        - dynamodb:DeleteTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: translate
          method: get
          cors: true
  
  create:
    handler: todos/create.create
    events:
      - http:
          path: create
          method: post
          cors: true

  list:
    handler: todos/list.list
    events:
      - http:
          path: list
          method: get
          cors: true

  createtable:
    handler: todos/createtable.create
    events:
      - http:
          path: createtable
          method: get

  deletetable:
    handler: todos/deletetable.delete
    events:
      - http:
          path: deletetable
          method: get
